version: '3.8'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  web:
    build: .
    command: sh -c "python manage.py migrate
               && python3 manage.py loaddata fixtures/ab.json
        && python3 manage.py loaddata fixtures/users.json
       && gunicorn DvgUpsAbiturient.wsgi:application --bind 0.0.0.0:8000
      && python3 manage.py bot"
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    restart: on-failure
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
      - redis


  dbAb:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod
  nginx:
    build: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - web
