version: '3.3'

services:
  web:
    build: .
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db

  db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: