version: '3.3'

services:
  backend:
    build: backend
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - backend_volume:/app
    entrypoint: ["sh", "entrypoint.sh"]
    ports:
      - "8000"
    env_file:
      - .env
    depends_on:
      - postgres_db
    environment:
      - POSTGRES_HOST=postgres_db
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq

  postgres_db:
    image: postgres:16
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:

  backend_volume:
