# Generated by Django 4.2.2 on 2023-07-09 13:45

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='study_forms',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Очная'), (2, 'Заочная'), (3, 'Очно-заочная')], max_length=5),
        ),
    ]
