# Generated by Django 4.2.2 on 2023-07-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abiturient', '0002_alter_speciality_study_forms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=140, unique=True, verbose_name='Специальность'),
        ),
    ]
