# Generated by Django 4.2.2 on 2024-06-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abiturient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('telegram_id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='имя в телеграмме')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='ник в телеграмме')),
                ('is_banned', models.BooleanField(default=False, verbose_name='забанен')),
                ('history', models.JSONField(blank=True, default=dict)),
                ('subjects', models.ManyToManyField(to='abiturient.exams', verbose_name='предметы ЕГЭ для поступления')),
            ],
            options={
                'verbose_name': 'Телеграм пользователь',
                'verbose_name_plural': 'Телеграм пользователи',
            },
        ),
    ]
